from django.urls import path

from users.api.views import (
    activity_feed,
    anime_reviews,
    create_review,
    dashboard,
    delete_review,
    favorite_ids,
    favorite_list,
    library,
    library_stats,
    my_reviews,
    profile,
    remove_from_library,
    review_analytics,
    toggle_favorite,
    top_rated_anime,
    update_profile,
    update_review,
    update_status,
)

urlpatterns = [
    path("profile/", profile),
    path("profile/update/", update_profile),
    path("favorites/", favorite_list),
    path("favorites/toggle/", toggle_favorite),
    path("favorites/ids/", favorite_ids),
    path("library/", library),
    path("library/update/", update_status),
    path("library/<int:anime_id>/", remove_from_library),
    path("activity/", activity_feed),
    path("library/stats/", library_stats),
    path("dashboard/", dashboard),
    path("reviews/", create_review),
    path("reviews/<int:anime_id>/", anime_reviews),
    path("reviews/<int:review_id>/update/", update_review),
    path("reviews/<int:review_id>/delete/", delete_review),
    path("reviews/my-reviews/", my_reviews),
    path("reviews/analytics/", review_analytics),
    path("reviews/top-rated/", top_rated_anime),
]
