# Generated by Django 5.2.13 on 2026-07-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('title_english', models.CharField(blank=True, default='', max_length=255)),
                ('search_title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('image_large', models.URLField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('rating', models.CharField(blank=True, default='', max_length=40)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, to='anime.genre')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
