# Generated by Django 5.2.13 on 2026-08-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_score_alter_anime_season_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['year'], name='anime_anime_year_38d697_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['season'], name='anime_anime_season_7d7132_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['type'], name='anime_anime_type_34feec_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['score'], name='anime_anime_score_fc3b7f_idx'),
        ),
    ]
