# Generated by Django 5.2.13 on 2026-08-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_anime_anime_year_38d697_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(unique=True),
        ),
    ]
