# Generated by Django 5.2.13 on 2026-09-03 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0004_alter_anime_mal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(
                fields=["created_at"],
                name="anime_anime_created_9f1d2a_idx",
            ),
        ),
    ]
