# Generated by Django 5.2.13 on 2026-09-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_anime_created_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='anime',
            new_name='anime_anime_created_1299d4_idx',
            old_name='anime_anime_created_9f1d2a_idx',
        ),
    ]
