# Generated by Django 5.2.13 on 2026-09-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_persist_supplementary_anime_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animetheme',
            options={'ordering': ['theme_type', 'position']},
        ),
        migrations.RenameIndex(
            model_name='animerelation',
            new_name='anime_anime_anime_i_df5b2a_idx',
            old_name='anime_animer_anime_i_9d5a4a_idx',
        ),
    ]
