# Generated by Django 5.2.13 on 2026-08-20 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_anime_anime_year_38d697_idx_and_more'),
        ('users', '0003_emailverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteanime',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='useranimestatus',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('plan_to_watch', 'Plan to Watch'), ('dropped', 'Dropped')], default='plan_to_watch', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='favoriteanime',
            constraint=models.UniqueConstraint(fields=('user', 'anime'), name='unique_user_anime_favorite'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'anime'), name='unique_user_anime_review'),
        ),
    ]
