# Generated by Django 5.2.13 on 2026-08-25 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_anime_anime_year_38d697_idx_and_more'),
        ('users', '0005_alter_activity_user_alter_favoriteanime_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='favoriteanime',
            name='users_favor_user_id_f08e3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='users_revie_anime_i_10262e_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='users_revie_user_id_136f8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='useranimestatus',
            name='users_usera_user_id_26d0b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='useranimestatus',
            name='users_usera_status_11bc24_idx',
        ),
        migrations.AddIndex(
            model_name='useranimestatus',
            index=models.Index(fields=['user', 'status'], name='users_usera_user_id_dd60ff_idx'),
        ),
    ]
