# Generated by Django 5.2.13 on 2026-08-25 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_anime_anime_year_38d697_idx_and_more'),
        ('users', '0006_remove_favoriteanime_users_favor_user_id_f08e3d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favoriteanime',
            index=models.Index(fields=['user', '-created_at'], name='users_favor_user_id_e0fb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['anime', '-created_at'], name='users_revie_anime_i_7f1bba_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='users_revie_user_id_20f0e4_idx'),
        ),
    ]
