# Generated by Django 5.2.13 on 2026-10-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_favoriteanime_users_favor_user_id_e0fb9e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token_hash',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
